portfolio/urls.py
from django.urls import path
from .views import index, contact, project_details, service_details

app_name = 'portfolio'

urlpatterns = [
    path('', index, name='index'),
    path('send-msg/', contact, name='contact'),
    path('service/<int:pk>', service_details, name='service-details'),
    path('project-details/<int:pk>', project_details, name='project-details'),
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from django_countries.fields import CountryField


# Create your models here.


class Project(models.Model):
    project_name = models.CharField(max_length=200)
    client = models.CharField(max_length=200)
    delivery_date = models.DateField()
    project_url = models.URLField(max_length=250)
    description = models.TextField()

    def __str__(self):
        return f'Project : {self.project_name} / URL : {self.project_url}'


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='projects/', blank=True)

    def __str__(self):
        return f'image:{self.image}'


class Testimonial(models.Model):
    customer_name = models.CharField(max_length=200)
    customer_image = models.ImageField(upload_to='customers/', blank=True)
    country = CountryField()
    quote = models.TextField()
    review_ranks = models.IntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)])

    def __str__(self):
        return f'{self.customer_name}'


class Service(models.Model):
    title_service = models.CharField(max_length=200)
    description_service = models.TextField()
    image_service = models.ImageField(upload_to='services', blank=True)

    def __str__(self):
        return self.title_service


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()
    datetime_message = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Name:{self.name},Message : {self.message[:20]}'

portfolio/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control mb-3', 'placeholder': 'email'})
        self.fields['message'].widget.attrs.update({'class': 'form-control mb-3', 'placeholder': 'message'})

portfolio/views.py
from django.shortcuts import render, redirect

# Create your views here.
from portfolio.forms import ContactForm
from portfolio.models import Project, ProjectImage, Service, Testimonial, Contact


def index(request):
    form_contact = ContactForm()
    data_projects = []
    projects = Project.objects.all()
    for p in projects:
        collect_data = {}
        project_images = ProjectImage.objects.filter(project__pk=p.pk).values_list('image', flat=True).first()
        project_ids = ProjectImage.objects.filter(project__pk=p.pk).values_list('project_id', flat=True)
        data = Project.objects.filter(id__in=project_ids)
        collect_data.update({'project': data, 'images': project_images})

        data_projects.append(collect_data)

    services = Service.objects.all()

    testimonials = Testimonial.objects.all()

    fetch_data = {'projects': data_projects, 'services': services, 'testimonials': testimonials, 'form': form_contact}
    return render(request, 'portfolio/index.html', context=fetch_data)


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        try:
            Contact.objects.create(name=name, email=email, message=message)
        except:
            return redirect('portfolio:index')
        return redirect('portfolio:index')


def project_details(request, pk):
    project_images = ProjectImage.objects.filter(project__pk=pk).values_list('image', flat=True)
    project = Project.objects.get(pk=pk)
    contex = {'project': project, 'project_images': project_images}
    return render(request, 'portfolio/project-details.html', context=contex)


def service_details(request, pk):
    service = Service.objects.get(pk=pk)
    contex = {'service': service}
    return render(request, 'portfolio/inner-page.html', context=contex)

portfolio/templates/portfolio/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- ======= Hero Section ======= -->
    {% include 'portfolio/temp_sections/hero.html' %}
    <main id="main">
        <!-- ======= About Section ======= -->
        {% include 'portfolio/temp_sections/about.html' %}
        <!-- ======= Resume Section ======= -->
        {#        {% include 'portfolio/temp_sections/resume.html' %}#}
        <!-- ======= Projects Section ======= -->

        <section id="portfolio" class="portfolio section-bg">
            <div class="container">

                <div class="section-title">
                    <h2>Projects</h2>
                    <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit
                        sint
                        consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                        Quia
                        fugiat sit in iste officiis commodi quidem hic quas.</p>
                </div>

                <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="100">
                    {% for list in projects %}
                        {% for project in list.project %}
                            <div class="col-lg-4 col-md-6 portfolio-item filter-app">
                                <div class="portfolio-wrap">
                                    <img src="images/{{ list.images }}" class="img-fluid" alt="">
                                    <div class="portfolio-links">
                                        <a href="images/{{ list.images }}"
                                           data-gallery="portfolioGallery"
                                           class="portfolio-lightbox" title="{{ project.project_name }}"><i
                                                class="bx bx-plus"></i></a>
                                        <a href="{% url 'portfolio:project-details' pk=project.pk %}"
                                           title="More Details"><i class="bx bx-link"></i></a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    {% endfor %}

                </div>
            </div>
        </section>
        <!-- End Portfolio Section -->

        <!-- ======= Services Section ======= -->
        <section id="services" class="services">
            <div class="container">

                <div class="section-title">
                    <h2>Services</h2>
                    <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit
                        sint
                        consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                        Quia
                        fugiat sit in iste officiis commodi quidem hic quas.</p>
                </div>

                <div class="row">

                    {% for service in services %}
                        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
                            <div class="icon">
                                <i class="bi bi-briefcase"></i>
                            </div>
                            <h4 class="title"><a
                                    href="{% url 'portfolio:service-details' pk=service.pk %}">{{ service.title_service }}</a>
                            </h4>
                            <p class="description">{{ service.description_service }}</p>
                        </div>
                    {% endfor %}

                </div>

            </div>
        </section><!-- End Services Section -->

        <!-- ======= Testimonials Section ======= -->
        <section id="testimonials" class="testimonials section-bg">
            <div class="container">

                <div class="section-title">
                    <h2>Testimonials</h2>
                    <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit
                        sint
                        consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                        Quia
                        fugiat sit in iste officiis commodi quidem hic quas.</p>
                </div>

                <div class="testimonials-slider swiper-container" data-aos="fade-up" data-aos-delay="100">
                    <div class="swiper-wrapper">
                        {% for testimonial in testimonials %}


                            <div class="swiper-slide">
                                <div class="testimonial-item" data-aos="fade-up">
                                    <p>
                                        <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                                        {{ testimonial.quote }}
                                        <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                                    </p>
                                    <img src="images/{{ testimonial.customer_image }}"
                                         class="testimonial-img"
                                         alt="">
                                    <h3>{{ testimonial.customer_name }}</h3>
                                    <h4>Country/{{ testimonial.country }}</h4>

                                </div>

                                  <div class="rating" data-default="{{ testimonial.review_ranks }}">
                                        <a>
                                            <div class="star1"></div>
                                        </a>
                                        <a>
                                            <div class="star2"></div>
                                        </a>
                                        <a>
                                            <div class="star3"></div>
                                        </a>
                                        <a>
                                            <div class="star4"></div>
                                        </a>
                                        <a>
                                            <div class="star5"></div>
                                        </a>
                                    </div>


                            </div><!-- End testimonial item -->


                        {% endfor %}


                    </div>
                    <div class="swiper-pagination"></div>
                </div>

            </div>
        </section><!-- End Testimonials Section -->

        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container">

                <div class="section-title">
                    <h2>Contact</h2>
                    <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit
                        sint
                        consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                        Quia
                        fugiat sit in iste officiis commodi quidem hic quas.</p>
                </div>

                <div class="row" data-aos="fade-in">

                    <div class="col-lg-5 d-flex align-items-stretch">
                        <div class="info">
                            <div class="address">
                                <i class="bi bi-geo-alt"></i>
                                <h4>Location:</h4>
                                <p>Palestine,Gaza ,PS 00790</p>
                            </div>

                            <div class="email">
                                <i class="bi bi-envelope"></i>
                                <h4>Email:</h4>
                                <p>harountaha@outlook.sa</p>
                            </div>

                            <div class="phone">
                                <i class="bi bi-phone"></i>
                                <h4>Call:</h4>
                                <p>+970597918088</p>
                            </div>

                            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621"
                                    frameborder="0" style="border:0; width: 100%; height: 290px;"
                                    allowfullscreen></iframe>
                        </div>

                    </div>

                    <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
                        <form action="{% url 'portfolio:contact' %}" method="post" class="php-email-form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label for="name">Your Name</label>
                                    {{ form.name }}
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="name">Your Email</label>
                                    {{ form.email }}
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="name">Message</label>
                                {{ form.message }}
                            </div>
                            <div class="my-3">
                                <div class="loading">Loading</div>
                                <div class="error-message"></div>
                                <div class="sent-message">Your message has been sent. Thank you!</div>
                            </div>
                            <div class="text-center">
                                <button type="submit">Send Message</button>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </section><!-- End Contact Section -->

    </main><!-- End #main -->

{% endblock %}

portfolio/templates/portfolio/inner-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>{{ service.title_service }}</h2>
          <ol>
            <li><a href="{% url 'portfolio:index' %}">Home</a></li>
            <li>Service Page</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">

        <div class="section-title">
            <h2>{{ service.title_service }}</h2>
            <!-- <p>I am a person who is passionate about technology. I love to work with Cloud based technologies. I have extensive knowledge on AWS and Microsoft Azure. For me Learning is an every day process to the exponential curve.</p> -->
        </div>
               <div class="row">
            <div class="col-lg-4" data-aos="fade-right">
                <img src="../images/{{ service.image_service }}" class="img-fluid" alt="">
            </div>
            <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
                <h3>Description</h3>
                <p></p>
                <p>
                    {{ service.description_service }}
                </p>
            </div>
        </div>

      </div>
    </section>

  </main><!-- End #main -->


{% endblock %}

portfolio/templates/portfolio/project-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs">
            <div class="container">

                <div class="d-flex justify-content-between align-items-center">
                    <h2>Project Details {{ project.project_name }}</h2>
                    <ol>
                        <li><a href="{% url 'portfolio:index' %}">Home</a></li>
                        <li>Project Details</li>
                    </ol>
                </div>

            </div>
        </section><!-- End Breadcrumbs -->

        <!-- ======= Portfolio Details Section ======= -->
        <section id="portfolio-details" class="portfolio-details">
            <div class="container">

                <div class="row gy-4">

                    <div class="col-lg-8">
                        <div class="portfolio-details-slider swiper-container">
                            <div class="swiper-wrapper align-items-center">

                                {% for image in project_images %}
                                    <div class="swiper-slide">
                                        <img src="../images/{{ image }}" alt="">
                                    </div>

                                {% endfor %}


                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="portfolio-info">
                            <h3>Project information</h3>
                            <ul>

                                <li><strong>Name project</strong>: {{ project.project_name}}</li>
                                <li><strong>Client</strong>: {{ project.client}}</li>
                                <li><strong>Project date</strong>: {{ project.delivery_date}}</li>
                                <li><strong>Project URL</strong>: <a href="#"> {{ project.project_url}}</a></li>
                            </ul>
                        </div>
                        <div class="portfolio-description">
                            <h2>This is an example of project description</h2>
                            <p>
                               {{ project.description }}
                            </p>
                        </div>
                    </div>

                </div>

            </div>
        </section><!-- End Portfolio Details Section -->

    </main><!-- End #main -->

{% endblock %}

portfolio/templates/portfolio/temp_sections/about.html
{% load static %}
<!-- ======= About Section ======= -->
<section id="about" class="about">
    <div class="container">

        <div class="section-title">
            <h2>About</h2>
            <!-- <p>I am a person who is passionate about technology. I love to work with Cloud based technologies. I have extensive knowledge on AWS and Microsoft Azure. For me Learning is an every day process to the exponential curve.</p> -->
        </div>

        <div class="row">
            <div class="col-lg-4" data-aos="fade-right">
                <img src="{% static 'img/IMG_57745.jpg' %}" class="img-fluid" alt="">
            </div>
            <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
                <h3>Backend Engineer at GGateway</h3>
                <p class="fst-italic">

                </p>
                <div class="row">
                    <div class="col-lg-6">
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong>
                                <span>5 Oct 1999</span></li>
                            <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong>
                                <span>www.pradeeprpin.in</span>
                            </li>
                            <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong>
                                <span>+970 597918088</span></li>
                            <li><i class="bi bi-chevron-right"></i> <strong>City:</strong>
                                <span>Palestine, Gaza.</span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <strong>Married Status:</strong>
                                <span>Single</span></li>
                            <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong>
                                <span>BE (CSE),</span>
                            </li>
                            <li><i class="bi bi-chevron-right"></i> <strong>PhEmailone:</strong> <span>harountaha@outlook.sa</span>
                            </li>
                            <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong>
                                <span>Available</span></li>
                        </ul>
                    </div>
                </div>
                <p>
                    I am a person who is passionate about technology. I love to work with Cloud based
                    technologies.
                    I have extensive knowledge on AWS and Microsoft Azure. For me Learning is an every day
                    process
                    to the exponential curve.
                </p>
            </div>
        </div>

    </div>
</section><!-- End About Section -->

portfolio/templates/portfolio/temp_sections/hero.html
{% load static %}

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex flex-column justify-content-center align-items-center">
        <div class="hero-container" data-aos="fade-in">
            <h1>Haroun Taha</h1>
            <!-- <p> I'm..<span class="typed" data-typed-items="Developer, Freelancer, Systems Engineer"></span></p> -->

            <p><span class="typed" data-typed-items="Python | Django | AWS 👨‍💻(🐱‍🏍◠‿◠)"></span></p>
        </div>
    </section><!-- End Hero -->

portfolio/templates/portfolio/temp_sections/resume.html
{% load static %}

        <!-- ======= Resume Section ======= -->
        <section id="resume" class="resume">
            <div class="container">

                <div class="section-title">
                    <h2>Resume</h2>
                    <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit
                        sint
                        consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                        Quia
                        fugiat sit in iste officiis commodi quidem hic quas.</p>
                </div>

                <div class="row">
                    <div class="col-lg-6" data-aos="fade-up">


                        <h3 class="resume-title">Education</h3>
                        <div class="resume-item">
                            <h4>Bachelor of Engineering</h4>
                            <h5>2017 - 2021</h5>
                            <p><em>Bannari Amman Institute of Technology, Sathyamangalam.</em></p>
                            <p>CGPA : 8.32 </p>
                        </div>
                        <div class="resume-item">
                            <h4>Higher Secondary Education</h4>
                            <h5>2015 - 2017</h5>
                            <p><em>Shree Gurukulam Higher Secondary School, Gobichettipalayam</em></p>
                            <p>Percentage : 80 %</p>
                        </div>
                        <div class="resume-item">
                            <h4>Secondary School Leaving Certificate</h4>
                            <h5>2014 - 2015</h5>
                            <p><em>Saru Matriculation Higher Secondary School, Sathyamangalam.</em></p>
                            <p>Percentage : 85 %</p>
                        </div>
                    </div>
                    <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
                        <h3 class="resume-title">Professional Experience</h3>
                        <div class="resume-item">
                            <h4>Systems Engineer</h4>
                            <h5>2021 - Present</h5>
                            <p><em>TATA CONSULTANCY SERVICES pvt ltd, Chennai.</em></p>
                            <ul>
                                <li> Digital Cadree.</li>
                                <li> Cognitive Bussniess Unit.</li>
                            </ul>
                        </div>
                        <div class="resume-item">
                            <h4>Student Intern </h4>
                            <h5>MARCH 2021 - JUNE 2021</h5>
                            <p><em>TATA CONSULTANCY SERVICES pvt ltd, Chennai</em></p>
                            <ul>
                                <li>Service Delivery Optimization.</li>
                                <li>Worked in NFV, AWS, Python Development, Automation.</li>
                            </ul>
                        </div>
                        <div class="resume-item">
                            <h4>DevOps Engineer</h4>
                            <h5>OCT 2020 - JAN 2021</h5>
                            <p><em>E-Cloudaeon, Pune.</em></p>
                            <ul>
                                <li>Linux Administration</li>
                                <li>Worked in Azure,DevOps Tools.</li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </section><!-- End Resume Section -->